import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Clock3, Eye, FileText, Filter, RotateCcw, Search, XCircle } from 'lucide-react';
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { Modal } from '../../components/ui/Modal';
import { KpiCard } from '../../components/ui/KpiCard';
import { dealerService, type DealerFinancingRequest } from '../../services/dealerService';
import { resolveApiUrl } from '../../api/apiClient';

const statusVariant = (status: DealerFinancingRequest['status']) => status === 'ACCEPTED' ? 'success' : status === 'REJECTED' ? 'danger' : status === 'PENDING' ? 'warning' : 'secondary';
const amount = (value?: number) => new Intl.NumberFormat('fr-TN', { minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(value || 0) + ' DT';
const date = (value?: string) => value ? new Date(value).toLocaleDateString('fr-TN') : '-';

export function DealerFinancingRequestsPage() {
  const [requests, setRequests] = useState<DealerFinancingRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [bankId, setBankId] = useState('');
  const [selected, setSelected] = useState<DealerFinancingRequest | null>(null);
  const load = async () => { setLoading(true); try { const response = await dealerService.financingRequests({ search: search || undefined, status: status || undefined, bankId: bankId ? Number(bankId) : undefined }); setRequests(response.data || []); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const banks = useMemo(() => [...new Map(requests.map(item => [item.bankId, item.bankName])).entries()], [requests]);
  const totals = useMemo(() => ({ all: requests.length, accepted: requests.filter(item => item.status === 'ACCEPTED').length, rejected: requests.filter(item => item.status === 'REJECTED').length, pending: requests.filter(item => item.status === 'PENDING').length }), [requests]);
  const reset = () => { setSearch(''); setStatus(''); setBankId(''); void (async () => { setLoading(true); try { const response = await dealerService.financingRequests(); setRequests(response.data || []); } finally { setLoading(false); } })(); };
  return <div className="mx-auto w-full max-w-[1280px] space-y-6 pb-8"><div><h1 className="text-3xl font-bold tracking-tight text-slate-900">Mes demandes de financement</h1><p className="mt-1 text-slate-500">Suivez les demandes soumises pour vos produits sur toutes les marketplaces partenaires.</p></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><KpiCard label="Demandes totales" value={totals.all} badge="Dossiers" tone="primary" icon={<FileText className="h-5 w-5" />} /><KpiCard label="Acceptées" value={totals.accepted} badge="Validées" tone="success" icon={<CheckCircle2 className="h-5 w-5" />} /><KpiCard label="Refusées" value={totals.rejected} badge="Décisions" tone="danger" icon={<XCircle className="h-5 w-5" />} /><KpiCard label="En attente" value={totals.pending} badge="À traiter" tone="warning" icon={<Clock3 className="h-5 w-5" />} /></div>
    <div className="grid w-full gap-3 overflow-x-auto rounded-2xl border border-slate-100 bg-white p-5 shadow-sm" style={{ gridTemplateColumns: 'minmax(340px, 1.5fr) minmax(190px, 0.8fr) minmax(190px, 0.8fr) auto auto' }}><label className="relative min-w-0"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={search} onChange={event => setSearch(event.target.value)} onKeyDown={event => event.key === 'Enter' && void load()} placeholder="Rechercher un client ou une référence" className="h-11 w-full rounded-lg border border-slate-200 pl-10 pr-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" /></label><select value={status} onChange={event => setStatus(event.target.value)} className="h-11 rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none"><option value="">Tous statuts</option><option value="PENDING">En attente</option><option value="ACCEPTED">Acceptée</option><option value="REJECTED">Rejetée</option></select><select value={bankId} onChange={event => setBankId(event.target.value)} className="h-11 rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none"><option value="">Toutes banques</option>{banks.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><Button className="h-11 whitespace-nowrap" icon={<Filter className="h-4 w-4" />} onClick={() => void load()}>Filtrer</Button><Button className="h-11 whitespace-nowrap" variant="outline" icon={<RotateCcw className="h-4 w-4" />} onClick={reset}>Réinitialiser</Button></div>
    <div className="overflow-x-auto rounded-2xl border border-slate-100 bg-white shadow-sm"><table className="w-full min-w-[1050px]"><thead className="border-b border-slate-100 bg-slate-50/80 text-left text-xs font-medium text-slate-500"><tr><th className="p-4">Référence</th><th className="p-4">Produit</th><th className="p-4">Client</th><th className="p-4">Banque</th><th className="p-4">Montant</th><th className="p-4">Date</th><th className="p-4">Statut</th><th className="p-4 text-right">Action</th></tr></thead><tbody>{loading ? <tr><td colSpan={8} className="p-12 text-center text-slate-500">Chargement des demandes…</td></tr> : requests.length === 0 ? <tr><td colSpan={8} className="p-12 text-center text-slate-500">Aucune demande trouvée.</td></tr> : requests.map(request => <tr key={request.id} className="border-b border-slate-100 last:border-0"><td className="p-4 text-sm font-semibold text-slate-700">{request.reference}</td><td className="p-4"><div className="flex items-center gap-3"><div className="flex h-10 w-12 items-center justify-center overflow-hidden rounded bg-slate-100">{request.productImageUrl && <img src={resolveApiUrl(request.productImageUrl)} className="h-full w-full object-contain" alt="" />}</div><span className="text-sm font-medium text-slate-700">{request.productName}</span></div></td><td className="p-4 text-sm text-slate-700">{request.clientName}</td><td className="p-4"><div className="flex items-center gap-2 text-sm text-slate-700">{request.bankLogoUrl && <img src={resolveApiUrl(request.bankLogoUrl)} className="h-7 w-7 rounded object-contain" alt="" />}{request.bankName}</div></td><td className="p-4 text-sm font-semibold text-slate-700">{amount(request.requestedAmount)}</td><td className="p-4 text-sm text-slate-600">{date(request.createdAt)}</td><td className="p-4"><Badge variant={statusVariant(request.status)}>{request.status}</Badge></td><td className="p-4 text-right"><Button size="sm" variant="outline" icon={<Eye className="h-4 w-4" />} onClick={() => setSelected(request)}>Voir</Button></td></tr>)}</tbody></table></div>
    <Modal isOpen={Boolean(selected)} onClose={() => setSelected(null)} title="Détail de la demande" size="lg"><div className="space-y-5"><div className="flex items-center justify-between rounded-xl bg-muted/40 p-4"><div><p className="text-sm text-muted-foreground">{selected?.reference}</p><h2 className="text-xl font-semibold">{selected?.productName}</h2></div>{selected && <Badge variant={statusVariant(selected.status)}>{selected.status}</Badge>}</div><div className="grid gap-4 sm:grid-cols-2"><Detail label="Montant financé" value={amount(selected?.requestedAmount)} /><Detail label="Mensualité" value={amount(selected?.monthlyPayment)} /><Detail label="Durée" value={selected?.durationMonths ? `${selected.durationMonths} mois` : '-'} /><Detail label="Demande créée le" value={date(selected?.createdAt)} /></div><div className="grid gap-4 rounded-xl border p-4 sm:grid-cols-2"><div><p className="text-xs uppercase text-muted-foreground">Client</p><p className="font-semibold">{selected?.clientName}</p><p className="text-sm">{selected?.clientEmail}</p><p className="text-sm">{selected?.clientPhone}</p></div><div><p className="text-xs uppercase text-muted-foreground">Banque et marketplace</p><p className="font-semibold">{selected?.bankName}</p><p className="text-sm">Store : {selected?.storeName}</p><p className="text-sm">Prix produit : {amount(selected?.productPrice)}</p></div></div><div className="flex justify-end"><Button variant="outline" onClick={() => setSelected(null)}>Fermer</Button></div></div></Modal>
  </div>;
}

function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-xs uppercase text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
